set(_CATKIN_CURRENT_PACKAGE "uuv_littoral_simulation")
set(uuv_littoral_simulation_VERSION "0.0.0")
set(uuv_littoral_simulation_MAINTAINER "ck <ck@todo.todo>")
set(uuv_littoral_simulation_PACKAGE_FORMAT "2")
set(uuv_littoral_simulation_BUILD_DEPENDS )
set(uuv_littoral_simulation_BUILD_EXPORT_DEPENDS )
set(uuv_littoral_simulation_BUILDTOOL_DEPENDS "catkin")
set(uuv_littoral_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(uuv_littoral_simulation_EXEC_DEPENDS )
set(uuv_littoral_simulation_RUN_DEPENDS )
set(uuv_littoral_simulation_TEST_DEPENDS )
set(uuv_littoral_simulation_DOC_DEPENDS )
set(uuv_littoral_simulation_URL_WEBSITE "")
set(uuv_littoral_simulation_URL_BUGTRACKER "")
set(uuv_littoral_simulation_URL_REPOSITORY "")
set(uuv_littoral_simulation_DEPRECATED "")